# Generated by Django 4.0.4 on 2022-05-03 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 17, 9, 29, 943916)),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 17, 9, 29, 943208)),
        ),
    ]
