# Generated by Django 4.0.4 on 2022-05-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_payment_date_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
