# Generated by Django 4.0.4 on 2022-05-05 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_payment_date_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room'),
        ),
    ]
