# Generated by Django 4.0.4 on 2022-05-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_client_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
