# Generated by Django 4.0.4 on 2022-05-07 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_registeration_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeration',
            name='income',
        ),
        migrations.AddField(
            model_name='payment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.registeration'),
        ),
    ]
