# Generated by Django 4.0.4 on 2022-05-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_registeration_income_payment_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='ects',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
