# Generated by Django 4.0.4 on 2022-05-07 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_room_ects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='room',
        ),
        migrations.RemoveField(
            model_name='registeration',
            name='date_left',
        ),
        migrations.AlterField(
            model_name='payment',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.history'),
        ),
    ]
