# Generated by Django 4.0.4 on 2022-05-07 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_history_cost_remove_payment_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.history'),
        ),
    ]
