# Generated by Django 4.0.4 on 2022-05-07 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_payment_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.history'),
        ),
    ]
